### ISSUE TITLE
Fix code to newer pyxel version

### ISSUE THREAD

**Issue by GitRenhl** [Vlek/Pyxel_Games#1]
Change this:
https://github.com/Vlek/Pyxel_Games/blob/a4de538f8e614857831eb3ca6cd27d4d59c78a00/Pong/Pong.py#L152-L154
to:
```
pyxel.rect(starting_x_pos, starting_y_pos, 
               marker_width, 
               marker_length, 7) 
```
------
Change this:
https://github.com/Vlek/Pyxel_Games/blob/a4de538f8e614857831eb3ca6cd27d4d59c78a00/Pong/Pong.py#L173-L174
to:
``` py
pyxel.rect(self.x, self.y,
           self.width, 
           self.height, 7) 
```
------
Change this:
https://github.com/Vlek/Pyxel_Games/blob/a4de538f8e614857831eb3ca6cd27d4d59c78a00/Pong/Pong.py#L147
to:
```py
marker_width = 1
```
------
Change this:
https://github.com/Vlek/Pyxel_Games/blob/a4de538f8e614857831eb3ca6cd27d4d59c78a00/Pong/Pong.py#L152-L154
to:
```py
 pyxel.rect(starting_x_pos, starting_y_pos, 
            marker_width, 
            marker_length, 7) 
```

**Comment by jlpjr1999** [comment]
Thanks for the changes. This fixed the layout!
